name: price_checker
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.0.1
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  awesome_dialog: ^1.1.3
  beautifulsoup: ^0.0.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
